#include "pch.h"

#include <string>

#include "obfuscate.h"
#include "hook_engine.h"
#include "hook_safety.h"
#include "process_identity.h"
#include "script_loader.h"
#if __has_include("encrypted_data.h")
#include "encrypted_data.h"
#else
// Stub: generated by scripts/generate_encrypted_header.ps1
static const EncryptedBlob g_enc_js_p1 = { nullptr, 0, 0 };
static const EncryptedBlob g_enc_js_p2 = { nullptr, 0, 0 };
#endif
#include "include/capi/cef_browser_capi.h"
#include "include/capi/cef_client_capi.h"
#include "include/capi/cef_frame_capi.h"
#include "include/capi/cef_life_span_handler_capi.h"
#include "include/capi/cef_load_handler_capi.h"
#include "include/internal/cef_types_win.h"
#include "include/internal/cef_win.h"

HMODULE g_hDll = NULL;

/* Page-level script injection guard */
static LONG g_pageScriptInjected = 0;

/* Hook installation state tracking */
static LONG g_hooksInstalled = 0;
static LONG g_hookRetryCount = 0;
static constexpr int HOOK_MAX_RETRIES    = 20;
static constexpr int HOOK_RETRY_DELAY_MS = 500;

/* =========================================================================
 * CEF function pointers & global state
 * ========================================================================= */
PVOID g_cef_browser_host_create_browser = NULL;
PVOID g_cef_on_load_end = NULL;
PVOID g_cef_on_loading_state_change = NULL;
PVOID g_cef_on_after_created = NULL;
PVOID g_cef_on_before_close = NULL;

static _cef_frame_t*   g_mainFrame   = NULL;
static _cef_browser_t* g_mainBrowser = NULL;

/* =========================================================================
 * GPU disable: GetCommandLineW Hook
 * ========================================================================= */
typedef LPWSTR(WINAPI* GetCommandLineW_t)(void);
static GetCommandLineW_t g_orig_GetCommandLineW = NULL;
static wchar_t g_cmdLineBuf[32768] = {0};

LPWSTR WINAPI MyGetCommandLineW(void) {
    if (g_cmdLineBuf[0] == 0 && g_orig_GetCommandLineW) {
        LPWSTR orig = g_orig_GetCommandLineW();
        if (orig && wcsstr(orig, L"--disable-gpu") == NULL) {
            _snwprintf_s(g_cmdLineBuf, _countof(g_cmdLineBuf), _TRUNCATE,
                         L"%s --disable-gpu --disable-gpu-compositing --use-angle=warp --disable-web-security --disable-site-isolation-trials",
                         orig);
            return g_cmdLineBuf;
        }
    }
    return g_cmdLineBuf[0] ? g_cmdLineBuf : g_orig_GetCommandLineW();
}

/* =========================================================================
 * CEF type definitions
 * ========================================================================= */
typedef int(CEF_EXPORT* cef_string_from_ptr_t)(const TCHAR*, size_t, cef_string_utf16_t*);
typedef void(CEF_EXPORT* cef_string_clear_t)(cef_string_utf16_t*);
cef_string_from_ptr_t func_cef_string_from_ptr = NULL;
cef_string_clear_t    func_cef_string_clear    = NULL;

typedef int(__cdecl* create_browser_t)(
    const cef_window_info_t*, struct _cef_client_t*,
    const cef_string_t*, const struct _cef_browser_settings_t*,
    struct _cef_dictionary_value_t*, struct _cef_request_context_t*);

typedef void(CEF_CALLBACK* on_loading_state_change_t)(
    struct _cef_load_handler_t*, struct _cef_browser_t*, int, int, int);

typedef void(CEF_CALLBACK* on_after_created_t)(
    struct _cef_life_span_handler_t*, struct _cef_browser_t*);

typedef void(CEF_CALLBACK* on_before_close_t)(
    struct _cef_life_span_handler_t*, struct _cef_browser_t*);

typedef void(CEF_CALLBACK* on_load_end_t)(
    struct _cef_load_handler_t*, struct _cef_browser_t*, struct _cef_frame_t*, int);

/* =========================================================================
 * Helpers
 * ========================================================================= */
static PVOID SafeReadVtableSlot(PVOID* vtable, int idx) {
    __try {
        PVOID val = vtable[idx];
        /* Basic sanity: pointer should be in a reasonable range */
        if (IsInvalidCodePointer(val))
            return NULL;
        return val;
    }
    __except (EXCEPTION_EXECUTE_HANDLER) { return NULL; }
}

static _cef_frame_t* GetMainFrame(_cef_browser_t* browser) {
    if (!browser) return NULL;
    return browser->get_main_frame(browser);
}

static void ExecJs(_cef_frame_t* frame, const TCHAR* jsCode) {
    if (!frame || !jsCode || !func_cef_string_from_ptr) return;
    cef_string_t eval = {0}, url = {0};
    func_cef_string_from_ptr(jsCode, _tcslen(jsCode), &eval);
    func_cef_string_from_ptr(TEXT(""), 0, &url);
    frame->execute_java_script(frame, &eval, &url, 0);
    if (func_cef_string_clear) {
        func_cef_string_clear(&eval);
        func_cef_string_clear(&url);
    }
}

/* =========================================================================
 * CEF Handler callbacks
 * ========================================================================= */

void CEF_CALLBACK MyOnLoadingStateChange(
    struct _cef_load_handler_t* self, struct _cef_browser_t* browser,
    int isLoading, int canGoBack, int canGoForward)
{
    (void)canGoBack; (void)canGoForward;
    if (isLoading) {
        InterlockedExchange(&g_pageScriptInjected, 0);
    } else {
        _cef_frame_t* frame = GetMainFrame(browser);
        if (frame) {
            g_mainFrame = frame;
            g_mainBrowser = browser;
        }
    }
    if (g_cef_on_loading_state_change)
        ((on_loading_state_change_t)g_cef_on_loading_state_change)(
            self, browser, isLoading, canGoBack, canGoForward);
}

void CEF_CALLBACK MyOnLoadEnd(
    struct _cef_load_handler_t* self, struct _cef_browser_t* browser,
    struct _cef_frame_t* frame, int httpStatusCode)
{
    if (frame) {
        const bool isMainFrame = frame->is_main(frame) != 0;
        g_mainFrame = frame;
        g_mainBrowser = browser;

        /* Auto-inject AutoExam into every frame. Some exam pages keep the
         * question DOM in a child frame; the JS guard prevents per-frame duplicates. */
        {
            char provider[128] = {0};
            char apiKey[4096] = {0};
            char textModel[256] = {0};
            char visionModel[256] = {0};
            char baseUrl[1024] = {0};
            char adapter[128] = {0};
            char supportsVision[16] = {0};
            GetEnvironmentVariableA("INJECTOR_AI_PROVIDER", provider, sizeof(provider));
            GetEnvironmentVariableA("INJECTOR_AI_KEY", apiKey, sizeof(apiKey));
            GetEnvironmentVariableA("INJECTOR_AI_TEXT_MODEL", textModel, sizeof(textModel));
            GetEnvironmentVariableA("INJECTOR_AI_VISION_MODEL", visionModel, sizeof(visionModel));
            GetEnvironmentVariableA("INJECTOR_AI_BASE_URL", baseUrl, sizeof(baseUrl));
            GetEnvironmentVariableA("INJECTOR_AI_ADAPTER", adapter, sizeof(adapter));
            GetEnvironmentVariableA("INJECTOR_AI_SUPPORTS_VISION", supportsVision, sizeof(supportsVision));
            if (!apiKey[0]) GetEnvironmentVariableA("INJECTOR_API_KEY", apiKey, sizeof(apiKey));

            auto jsEscape = [](const char* s) -> std::string {
                std::string out;
                for (; *s; ++s) {
                    switch (*s) {
                    case '\\': out += "\\\\"; break;
                    case '\'': out += "\\'"; break;
                    case '"':  out += "\\\""; break;
                    case '\n': out += "\\n"; break;
                    case '\r': out += "\\r"; break;
                    case '\t': out += "\\t"; break;
                    default:
                        if ((unsigned char)*s < 0x20) {
                            char buf[8]; sprintf_s(buf, "\\x%02x", (unsigned char)*s);
                            out += buf;
                        } else {
                            out += *s;
                        }
                    }
                }
                return out;
            };

            std::string js;
            js = "if(!window.__AUTOEXAM_INJECTED__){window.__AUTOEXAM_INJECTED__=true;\n";
            if (apiKey[0]) {
                js += "window.__DEEPSEEK_API_KEY='";
                js += jsEscape(apiKey);
                js += "';\n";
                js += "window.__AUTOEXAM_AI_CONFIG={provider:'";
                js += jsEscape(provider[0] ? provider : "deepseek");
                js += "',apiKey:'";
                js += jsEscape(apiKey);
                js += "',baseUrl:'";
                js += jsEscape(baseUrl[0] ? baseUrl : "https://api.deepseek.com");
                js += "',textModel:'";
                js += jsEscape(textModel[0] ? textModel : "deepseek-chat");
                js += "',visionModel:'";
                js += jsEscape(visionModel[0] ? visionModel : (textModel[0] ? textModel : "deepseek-chat"));
                js += "',adapter:'";
                js += jsEscape(adapter[0] ? adapter : "openai-chat");
                js += "',supportsVision:";
                js += (supportsVision[0] == '1') ? "true" : "false";
                js += "};\n";
            }
            std::string remoteScript;
            std::string remoteVersion;
            if (FetchVersionedScript(&remoteScript, &remoteVersion)) {
                js += remoteScript;
            } else {
                // Fallback keeps old clients usable if the script service is unavailable.
                std::string jsP1((const char*)g_enc_js_p1.data, g_enc_js_p1.size);
                DecryptBytesInPlace((BYTE*)&jsP1[0], jsP1.size(), g_enc_js_p1.key);
                js += jsP1;
                std::string jsP2((const char*)g_enc_js_p2.data, g_enc_js_p2.size);
                DecryptBytesInPlace((BYTE*)&jsP2[0], jsP2.size(), g_enc_js_p2.key);
                js += jsP2;
            }
            js += "\n}\n";

            int wideLen = MultiByteToWideChar(CP_UTF8, 0, js.data(), (int)js.size(), NULL, 0);
            if (wideLen > 0) {
                WCHAR* wideBuf = new WCHAR[wideLen + 1];
                MultiByteToWideChar(CP_UTF8, 0, js.data(), (int)js.size(), wideBuf, wideLen);
                wideBuf[wideLen] = L'\0';
                ExecJs(frame, wideBuf);
                delete[] wideBuf;
            }

            char injectDbg[96];
            sprintf_s(injectDbg, "[HOOK] AutoExam script injected frame=%s\n", isMainFrame ? "main" : "sub");
            OutputDebugStringA(injectDbg);
        }
    }
    if (g_cef_on_load_end)
        ((on_load_end_t)g_cef_on_load_end)(self, browser, frame, httpStatusCode);
}

void CEF_CALLBACK MyOnAfterCreated(
    struct _cef_life_span_handler_t* self, struct _cef_browser_t* browser)
{
    g_mainBrowser = browser;
    _cef_frame_t* frame = GetMainFrame(browser);
    if (frame) g_mainFrame = frame;
    if (g_cef_on_after_created)
        ((on_after_created_t)g_cef_on_after_created)(self, browser);
}

void CEF_CALLBACK MyOnBeforeClose(
    struct _cef_life_span_handler_t* self, struct _cef_browser_t* browser)
{
    if (g_cef_on_before_close)
        ((on_before_close_t)g_cef_on_before_close)(self, browser);
}

/* =========================================================================
 * Dynamic vtable offset detection
 *
 * CEF client vtable layout varies between versions. We probe multiple
 * candidate offsets to find the get_load_handler and get_life_span_handler
 * slots rather than relying on hardcoded offsets.
 * ========================================================================= */

/* Candidate vtable slot indices for get_load_handler */
static const int LOAD_HANDLER_SLOTS[] = { 11, 12, 13, 10, 14, 9 };
static constexpr int LOAD_HANDLER_SLOT_COUNT = sizeof(LOAD_HANDLER_SLOTS) / sizeof(LOAD_HANDLER_SLOTS[0]);

/* Candidate vtable slot indices for get_life_span_handler */
static const int LIFE_SPAN_HANDLER_SLOTS[] = { 10, 11, 12, 9, 13, 8 };
static constexpr int LIFE_SPAN_HANDLER_SLOT_COUNT = sizeof(LIFE_SPAN_HANDLER_SLOTS) / sizeof(LIFE_SPAN_HANDLER_SLOTS[0]);

/* Try to hook load handler by probing multiple vtable offsets */
static void TryHookLoadHandler(struct _cef_client_t* client) {
    if (g_cef_on_load_end && g_cef_on_loading_state_change) return;

    PVOID* vtable = (PVOID*)((BYTE*)client + CefClientHandlerTableOffset());

    for (int i = 0; i < (int)LOAD_HANDLER_SLOT_COUNT; i++) {
        int slot = LOAD_HANDLER_SLOTS[i];
        PVOID ldSlot = SafeReadVtableSlot(vtable, slot);
        if (!ldSlot) continue;

        typedef struct _cef_load_handler_t*(CEF_CALLBACK* get_ld_t)(struct _cef_client_t*);
        struct _cef_load_handler_t* lh = ((get_ld_t)ldSlot)(client);
        if (!lh) continue;

        if (lh->on_loading_state_change && !g_cef_on_loading_state_change) {
            g_cef_on_loading_state_change = (PVOID)lh->on_loading_state_change;
            HookAttach(&g_cef_on_loading_state_change, MyOnLoadingStateChange);
        }
        if (lh->on_load_end && !g_cef_on_load_end) {
            g_cef_on_load_end = (PVOID)lh->on_load_end;
            HookAttach(&g_cef_on_load_end, MyOnLoadEnd);
        }

        if (g_cef_on_load_end && g_cef_on_loading_state_change) {
            char dbg[128];
            sprintf_s(dbg, "[HOOK] LoadHandler hooked at slot %d\n", slot);
            OutputDebugStringA(dbg);
            return;
        }
    }
    OutputDebugStringA("[HOOK] WARNING: LoadHandler not found at any candidate slot\n");
}

/* Try to hook life span handler by probing multiple vtable offsets */
static void TryHookLifeSpanHandler(struct _cef_client_t* client) {
    if (g_cef_on_after_created && g_cef_on_before_close) return;

    PVOID* vtable = (PVOID*)((BYTE*)client + CefClientHandlerTableOffset());

    for (int i = 0; i < (int)LIFE_SPAN_HANDLER_SLOT_COUNT; i++) {
        int slot = LIFE_SPAN_HANDLER_SLOTS[i];
        PVOID lsSlot = SafeReadVtableSlot(vtable, slot);
        if (!lsSlot) continue;

        typedef struct _cef_life_span_handler_t*(CEF_CALLBACK* get_ls_t)(struct _cef_client_t*);
        struct _cef_life_span_handler_t* lsh = ((get_ls_t)lsSlot)(client);
        if (!lsh) continue;

        if (lsh->on_after_created && !g_cef_on_after_created) {
            g_cef_on_after_created = (PVOID)lsh->on_after_created;
            HookAttach(&g_cef_on_after_created, MyOnAfterCreated);
        }
        if (lsh->on_before_close && !g_cef_on_before_close) {
            g_cef_on_before_close = (PVOID)lsh->on_before_close;
            HookAttach(&g_cef_on_before_close, MyOnBeforeClose);
        }

        if (g_cef_on_after_created && g_cef_on_before_close) {
            char dbg[128];
            sprintf_s(dbg, "[HOOK] LifeSpanHandler hooked at slot %d\n", slot);
            OutputDebugStringA(dbg);
            return;
        }
    }
    OutputDebugStringA("[HOOK] WARNING: LifeSpanHandler not found at any candidate slot\n");
}

/* =========================================================================
 * create_browser Hook
 * ========================================================================= */
int __cdecl MyCreateBrowser(
    const cef_window_info_t* windowInfo, struct _cef_client_t* client,
    const cef_string_t* url, const struct _cef_browser_settings_t* settings,
    struct _cef_dictionary_value_t* extra_info,
    struct _cef_request_context_t* request_context)
{
    if (client) {
        if (!g_cef_on_after_created || !g_cef_on_before_close) TryHookLifeSpanHandler(client);
        if (!g_cef_on_load_end || !g_cef_on_loading_state_change) TryHookLoadHandler(client);
    }
    create_browser_t orig = (create_browser_t)g_cef_browser_host_create_browser;
    return orig(windowInfo, client, url, settings, extra_info, request_context);
}

/* =========================================================================
 * Screen capture prevention
 * ========================================================================= */
typedef BOOL(WINAPI* set_affinity_t)(HWND, DWORD);
PVOID g_set_window_display_affinity = NULL;

BOOL WINAPI MySetWindowDisplayAffinity(HWND hWnd, DWORD dwAffinity) {
    if (dwAffinity == WDA_MONITOR) return TRUE;
    if (g_set_window_display_affinity)
        return ((set_affinity_t)g_set_window_display_affinity)(hWnd, dwAffinity);
    return TRUE;
}

/* =========================================================================
 * InstallHook — install all hooks with retry logic
 * ========================================================================= */
BOOL APIENTRY InstallHook() {
    OutputDebugString(TEXT("[HOOK] Installing all hooks...\n"));

    /* 1. GPU software rendering */
    g_orig_GetCommandLineW = (GetCommandLineW_t)
        HookFindFunction("kernel32.dll", "GetCommandLineW");
    if (g_orig_GetCommandLineW) {
        LONG r = HookAttach((PVOID*)&g_orig_GetCommandLineW, (PVOID)MyGetCommandLineW);
        if (r != ERROR_SUCCESS) {
            char dbg[128];
            sprintf_s(dbg, "[HOOK] GetCommandLineW hook failed: %ld\n", r);
            OutputDebugStringA(dbg);
        }
    }

    /* 2. create_browser */
    g_cef_browser_host_create_browser =
        HookFindFunction("libcef.dll", "cef_browser_host_create_browser");
    if (g_cef_browser_host_create_browser) {
        LONG r = HookAttach(&g_cef_browser_host_create_browser, (PVOID)MyCreateBrowser);
        if (r != ERROR_SUCCESS) {
            char dbg[128];
            sprintf_s(dbg, "[HOOK] create_browser hook failed: %ld\n", r);
            OutputDebugStringA(dbg);
            return FALSE;
        }
    } else {
        OutputDebugString(TEXT("[HOOK] FATAL: create_browser not found\n"));
        return FALSE;
    }

    /* 3. CEF string utilities */
#ifdef UNICODE
    func_cef_string_from_ptr = (cef_string_from_ptr_t)
        HookFindFunction("libcef.dll", "cef_string_wide_to_utf16");
    func_cef_string_clear = (cef_string_clear_t)
        HookFindFunction("libcef.dll", "cef_string_utf16_clear");
#else
    func_cef_string_from_ptr = (cef_string_from_ptr_t)
        HookFindFunction("libcef.dll", "cef_string_ascii_to_utf16");
    func_cef_string_clear = (cef_string_clear_t)
        HookFindFunction("libcef.dll", "cef_string_utf8_clear");
#endif

    /* 4. Screen capture prevention */
    g_set_window_display_affinity =
        HookFindFunction("user32.dll", "SetWindowDisplayAffinity");
    if (g_set_window_display_affinity)
        HookAttach(&g_set_window_display_affinity, (PVOID)MySetWindowDisplayAffinity);

    return TRUE;
}

/* =========================================================================
 * Worker thread entry with retry logic
 * ========================================================================= */
DWORD WINAPI ThreadProc(LPVOID lpThreadParameter) {
    (void)lpThreadParameter;
    Sleep(100);
    LogCurrentProcessIdentity();

    /* Initial hook installation */
    DWORD t0 = GetTickCount();
    if (InstallHook()) {
        InterlockedExchange(&g_hooksInstalled, 1);
        OutputDebugString(TEXT("[HOOK] All hooks installed successfully\n"));
    } else {
        OutputDebugString(TEXT("[HOOK] Some hooks FAILED - will retry on next browser creation\n"));
    }

    /* Periodic self-healing: check if hooks are still intact.
     * Some CEF versions reload DLLs or re-initialize vtables.
     * This loop runs for a limited time after injection. */
    for (int retry = 0; retry < HOOK_MAX_RETRIES; retry++) {
        Sleep(HOOK_RETRY_DELAY_MS);

        /* Check if main CEF hooks are still active */
        if (g_cef_browser_host_create_browser &&
            g_cef_on_load_end && g_cef_on_after_created) {
            /* All hooks active — continue monitoring */
            continue;
        }

        /* Some hooks missing — try to re-install */
        if (!g_cef_browser_host_create_browser) {
            PVOID addr = HookFindFunction("libcef.dll", "cef_browser_host_create_browser");
            if (addr) {
                g_cef_browser_host_create_browser = addr;
                HookAttach(&g_cef_browser_host_create_browser, (PVOID)MyCreateBrowser);
                OutputDebugStringA("[HOOK] Re-hooked create_browser\n");
            }
        }
    }

    DWORD t1 = GetTickCount();
    char dbg[128];
    sprintf_s(dbg, "[HOOK] Hook thread completed after %lu ms\n", t1 - t0);
    OutputDebugStringA(dbg);

    return 0;
}
