param(
    [int]$TargetSizeMB = 7,
    [string]$OutHeader = "src/padding_data.h"
)

$ErrorActionPreference = 'Stop'

$tableSize = 65536
$numTables = [math]::Floor(($TargetSizeMB * 1024 * 1024) / $tableSize / 2)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Auto-generated padding data for binary obfuscation")
[void]$sb.AppendLine("// DO NOT EDIT - generated by scripts/gen_padding.ps1")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <windows.h>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace padding {")
[void]$sb.AppendLine("")

$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()

for ($t = 0; $t -lt $numTables; $t++) {
    $data = New-Object byte[] $tableSize
    $rng.GetBytes($data)

    $xorByte = [byte]($t -band 0xFF)
    for ($i = 0; $i -lt $tableSize; $i++) {
        $data[$i] = $data[$i] -bxor ($xorByte -bxor ($i -band 0xFF))
    }

    [void]$sb.AppendLine("static const BYTE g_pad_$t [$tableSize] = {")

    for ($i = 0; $i -lt $tableSize; $i += 16) {
        $end = [math]::Min($i + 16, $tableSize) - 1
        $hexParts = @()
        for ($j = $i; $j -le $end; $j++) {
            $hexParts += "0x$($data[$j].ToString('X2'))"
        }
        $line = "    " + ($hexParts -join ", ")
        if ($end -lt $tableSize - 1) { $line += "," }
        [void]$sb.AppendLine($line)
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
}

[void]$sb.AppendLine("static volatile BYTE g_padXor = 0;")
[void]$sb.AppendLine("static void TouchPadding() {")
[void]$sb.AppendLine("    volatile BYTE x = 0;")
for ($t = 0; $t -lt $numTables; $t++) {
    [void]$sb.AppendLine("    x ^= g_pad_$t[0]; x ^= g_pad_$t[$tableSize - 1];")
}
[void]$sb.AppendLine("    g_padXor = x;")
[void]$sb.AppendLine("}")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("} // namespace padding")

$outPath = Join-Path (Join-Path $PSScriptRoot "..") $OutHeader
$content = $sb.ToString()
[System.IO.File]::WriteAllText($outPath, $content, [System.Text.Encoding]::UTF8)

$sizeMB = [math]::Round((Get-Item $outPath).Length / 1MB, 2)
Write-Host "Generated padding: $numTables tables x 64KB = $($numTables * 64)KB raw data" -ForegroundColor Green
Write-Host "Header file: $outPath ($sizeMB MB)" -ForegroundColor Green
