param(
    [Parameter(Mandatory=$true)] [string]$JsFile,
    [Parameter(Mandatory=$true)] [string]$OutHeader
)

<#
.SYNOPSIS
    Encrypts AutoExam_silent.js and all sensitive config strings into a single
    C header file (encrypted_data.h).  The DLL/EXE includes this header and
    decrypts at runtime via obfuscate.h.

.EXAMPLE
    .\generate_encrypted_header.ps1 -JsFile ..\AutoExam_silent.js -OutHeader ..\src\encrypted_data.h
#>

$ErrorActionPreference = 'Stop'

# ============================================================
# XOR encrypt function (must match obfuscate.h::DecryptBytesInPlace)
# ============================================================
function Encrypt-Bytes {
    param([byte[]]$Data, [UInt64]$Key)
    $kb = [System.BitConverter]::GetBytes($Key)
    $out = New-Object byte[] $Data.Length
    for ($i = 0; $i -lt $Data.Length; $i++) {
        $out[$i] = $Data[$i] -bxor $kb[$i -band 7] -bxor ([byte](($i * 0x9D) -band 0xFF))
    }
    return $out
}

function Format-CArray {
    param([byte[]]$Data, [string]$Indent = '    ')
    $lines = @()
    for ($i = 0; $i -lt $Data.Length; $i += 16) {
        $line = $Indent
        for ($j = $i; $j -lt [Math]::Min($i + 16, $Data.Length); $j++) {
            $line += "0x{0:X2}, " -f $Data[$j]
        }
        $lines += $line.TrimEnd()
    }
    return $lines -join "`n"
}

function New-RandomKey { [UInt64](Get-Random -Minimum 1 -Maximum ([Int64]::MaxValue)) }

# ============================================================
# Sensitive strings (ANSI = UTF8, WIDE = UTF16-LE)
# ============================================================
$strings = @{
    kHost         = @{ text = "47.110.248.240";     wide = $true  }
    kClientId     = @{ text = "injector_v1";         wide = $true  }
    kSecret       = @{ text = "c1a3f8e9d2b47a6e8f0c3d5b9a1e4f7a8b2c6d0e3f5a7b9c1d4e6f8a0b2c4d6"; wide = $false }
    kPathActivate = @{ text = "/api/v1/activate";    wide = $true  }
    kPathHeartbeat= @{ text = "/api/v1/heartbeat";   wide = $true  }
    kPathDeact    = @{ text = "/api/v1/deactivate";  wide = $true  }
    kPathAnnounce = @{ text = "/api/v1/announcement";wide = $true  }
}

# ============================================================
# Read and encrypt JS file
# ============================================================
Write-Host "Reading $JsFile ..." -ForegroundColor Cyan
$jsContent = [System.IO.File]::ReadAllText((Resolve-Path $JsFile))
$jsBytes   = [System.Text.Encoding]::UTF8.GetBytes($jsContent)
Write-Host "  JS size: $($jsBytes.Length) bytes" -ForegroundColor Gray

# Split JS at the same point as thread.cpp (L404: )AUTOEXAM" → end of p1)
# The split marker is the end of the first raw string literal.
# In the original code, g_autoExamScript_p1 ends at fillAnswerAsync closing
# and g_autoExamScript_p2 starts with hasNextQuestion.
$splitMarker = [regex]::Match($jsContent, '(?<=function fillAnswerAsync\(question, answer\) \{[\s\S]*?\}\r?\n)(?=\s*function hasNextQuestion)')
if ($splitMarker.Success) {
    $splitPos = $splitMarker.Index
    Write-Host "  Found split point at byte offset: $splitPos" -ForegroundColor Gray
} else {
    # Fallback: split roughly in half
    $splitPos = [Math]::Floor($jsContent.Length / 2)
    Write-Host "  WARNING: Could not find exact split marker. Using midpoint: $splitPos" -ForegroundColor Yellow
}

$jsP1 = $jsContent.Substring(0, $splitPos)
$jsP2 = $jsContent.Substring($splitPos)

$p1Bytes = [System.Text.Encoding]::UTF8.GetBytes($jsP1)
$p2Bytes = [System.Text.Encoding]::UTF8.GetBytes($jsP2)
Write-Host "  Part 1: $($p1Bytes.Length) bytes, Part 2: $($p2Bytes.Length) bytes" -ForegroundColor Gray

# ============================================================
# Generate encrypted blobs
# ============================================================
$encrypted = @{}
foreach ($name in $strings.Keys) {
    $s = $strings[$name]
    if ($s.wide) {
        $raw = [System.Text.Encoding]::Unicode.GetBytes($s.text)
    } else {
        $raw = [System.Text.Encoding]::UTF8.GetBytes($s.text)
    }
    $key = New-RandomKey
    $encrypted[$name] = @{ data = (Encrypt-Bytes $raw $key); key = $key }
    Write-Host "  Encrypted $name : $($raw.Length) raw bytes → $($encrypted[$name].data.Length) encrypted" -ForegroundColor Gray
}

$jsKey1 = New-RandomKey
$jsKey2 = New-RandomKey
$encJsP1 = @{ data = (Encrypt-Bytes $p1Bytes $jsKey1); key = $jsKey1 }
$encJsP2 = @{ data = (Encrypt-Bytes $p2Bytes $jsKey2); key = $jsKey2 }
Write-Host "  Encrypted JS Part 1: $($encJsP1.data.Length) bytes" -ForegroundColor Gray
Write-Host "  Encrypted JS Part 2: $($encJsP2.data.Length) bytes" -ForegroundColor Gray

# ============================================================
# Write header
# ============================================================
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Auto-generated by scripts/generate_encrypted_header.ps1")
[void]$sb.AppendLine("// DO NOT EDIT MANUALLY — regenerate with:")
[void]$sb.AppendLine("//   pwsh scripts/generate_encrypted_header.ps1 -JsFile AutoExam_silent.js -OutHeader src/encrypted_data.h")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine('#include "obfuscate.h"')
[void]$sb.AppendLine("")

# String blobs
foreach ($name in ($strings.Keys | Sort-Object)) {
    $e = $encrypted[$name]
    $varname = "g_enc_$name"
    [void]$sb.AppendLine("// $name")
    [void]$sb.AppendLine("static const BYTE __${varname}_data[] = {")
    [void]$sb.AppendLine((Format-CArray $e.data))
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("static const EncryptedBlob ${varname} = {")
    [void]$sb.AppendLine("    __${varname}_data,")
    [void]$sb.AppendLine("    $($e.data.Length),")
    [void]$sb.AppendLine("    0x$($e.key.ToString('X16'))ULL")
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
}

# JS parts
[void]$sb.AppendLine("// AutoExam JS Part 1 (encrypted)")
[void]$sb.AppendLine("static const BYTE __g_enc_js_p1_data[] = {")
[void]$sb.AppendLine((Format-CArray $encJsP1.data))
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const EncryptedBlob g_enc_js_p1 = {")
[void]$sb.AppendLine("    __g_enc_js_p1_data,")
[void]$sb.AppendLine("    $($encJsP1.data.Length),")
[void]$sb.AppendLine("    0x$($encJsP1.key.ToString('X16'))ULL")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")

[void]$sb.AppendLine("// AutoExam JS Part 2 (encrypted)")
[void]$sb.AppendLine("static const BYTE __g_enc_js_p2_data[] = {")
[void]$sb.AppendLine((Format-CArray $encJsP2.data))
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const EncryptedBlob g_enc_js_p2 = {")
[void]$sb.AppendLine("    __g_enc_js_p2_data,")
[void]$sb.AppendLine("    $($encJsP2.data.Length),")
[void]$sb.AppendLine("    0x$($encJsP2.key.ToString('X16'))ULL")
[void]$sb.AppendLine("};")

$outPath = (Resolve-Path (Split-Path $OutHeader -Parent))
$outName = Split-Path $OutHeader -Leaf
$fullOut = Join-Path $outPath $outName
[System.IO.File]::WriteAllText($fullOut, $sb.ToString())

Write-Host "`n✓ Generated $fullOut" -ForegroundColor Green
Write-Host "  Encrypted strings: $($strings.Count)" -ForegroundColor Green
Write-Host "  JS Part 1: $($encJsP1.data.Length) bytes" -ForegroundColor Green
Write-Host "  JS Part 2: $($encJsP2.data.Length) bytes" -ForegroundColor Green
