#pragma once
#include <windows.h>

// ============================================================================
// Lightweight XOR string obfuscation
// Each encrypted string uses a random 64-bit key.  Decryption is 3-4 cycles
// per byte — negligible overhead even for large (100KB+) strings.
//
// Usage:
//   #include "obfuscate.h"
//   const auto pw = DECRYPT_W(g_enc_password);
//   wprintf(L"%s\n", pw.c_str());
// ============================================================================

struct EncryptedBlob {
    const BYTE* data;
    size_t      size;
    DWORD64     key;
};

// ---- raw C utility ------------------------------------------------
inline void DecryptBytesInPlace(BYTE* buf, size_t len, DWORD64 key) {
    BYTE k[8];
    memcpy(k, &key, 8);
    for (size_t i = 0; i < len; i++) buf[i] ^= k[i & 7] ^ (BYTE)((i * 0x9D) & 0xFF);
}

// ---- C++ RAII helper (auto-clears on destruction) -----------------
template <typename CharT>
struct SecBuf {
    CharT*   ptr;
    size_t   len;   // in CharT units
    DWORD64  key;

    SecBuf(const EncryptedBlob& blob) : ptr(nullptr), len(0), key(blob.key) {
        len = blob.size / sizeof(CharT);
        ptr = new CharT[len + 1];
        memcpy(ptr, blob.data, blob.size);
        DecryptBytesInPlace((BYTE*)ptr, blob.size, key);
        ptr[len] = 0;
    }
    ~SecBuf() {
        if (ptr) {
            SecureZeroMemory(ptr, len * sizeof(CharT));
            delete[] ptr;
        }
    }
    SecBuf(const SecBuf&) = delete;
    SecBuf& operator=(const SecBuf&) = delete;

    CharT*       c_str()       { return ptr; }
    const CharT* c_str() const { return ptr; }
};

// ---- Convenience macros for passing encrypted strings -------------
// EncryptedBlob is generated by scripts/encrypt_strings.ps1
#define DECRYPT_A(blob)  (SecBuf<char>  (blob).c_str())
#define DECRYPT_W(blob)  (SecBuf<WCHAR> (blob).c_str())
#define DECRYPT_S(blob)  (SecBuf<char>(blob))    // RAII, holds until scope exit
#define DECRYPT_WS(blob) (SecBuf<WCHAR>(blob))   // RAII, holds until scope exit

// ============================================================================
// Anti-analysis: API hashing (compile-time FNV-1a)
// Hides API names from strings table, defeats static string analysis.
// Usage: HashApiName("LoadLibraryW") at compile-time, lookup by hash at runtime.
// ============================================================================
constexpr DWORD HashApiName(const char* name) {
    DWORD hash = 0x811c9dc5; // FNV offset basis
    for (int i = 0; name[i]; i++) {
        hash ^= (BYTE)name[i];
        hash *= 0x01000193; // FNV prime
    }
    return hash;
}

// Runtime API hash lookup — finds export by hash instead of name
static PVOID GetApiByHash(HMODULE hModule, DWORD targetHash) {
    if (!hModule) return NULL;
    BYTE* base = (BYTE*)hModule;
    __try {
        IMAGE_DOS_HEADER* dos = (IMAGE_DOS_HEADER*)base;
        if (dos->e_magic != IMAGE_DOS_SIGNATURE) return NULL;
        IMAGE_NT_HEADERS* nt = (IMAGE_NT_HEADERS*)(base + dos->e_lfanew);
        if (nt->Signature != IMAGE_NT_SIGNATURE) return NULL;
        IMAGE_DATA_DIRECTORY* expDir = &nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT];
        if (expDir->VirtualAddress == 0) return NULL;

        IMAGE_EXPORT_DIRECTORY* exp = (IMAGE_EXPORT_DIRECTORY*)(base + expDir->VirtualAddress);
        DWORD* names = (DWORD*)(base + exp->AddressOfNames);
        WORD* ordinals = (WORD*)(base + exp->AddressOfNameOrdinals);
        DWORD* funcs = (DWORD*)(base + exp->AddressOfFunctions);

        for (DWORD i = 0; i < exp->NumberOfNames; i++) {
            const char* name = (const char*)(base + names[i]);
            DWORD hash = 0x811c9dc5;
            for (int j = 0; name[j]; j++) {
                hash ^= (BYTE)name[j];
                hash *= 0x01000193;
            }
            if (hash == targetHash) {
                return (PVOID)(base + funcs[ordinals[i]]);
            }
        }
    }
    __except (EXCEPTION_EXECUTE_HANDLER) { return NULL; }
    return NULL;
}
